# Generated by Django 3.2 on 2023-03-28 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet_exercise_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='name',
        ),
        migrations.AddField(
            model_name='diet',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='goal',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('maintain', 'Maintain')], default='maintain', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diet',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
