# Generated by Django 3.2 on 2023-03-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_exercise_app', '0002_auto_20230328_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet',
            old_name='height',
            new_name='weight_lbs',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='weight',
        ),
        migrations.AddField(
            model_name='diet',
            name='feet',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='inches',
            field=models.IntegerField(null=True),
        ),
    ]
