# Generated by Django 3.2 on 2023-03-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_exercise_app', '0003_auto_20230328_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet',
            old_name='feet',
            new_name='height',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='inches',
        ),
    ]
