# Generated by Django 3.2 on 2023-03-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_exercise_app', '0004_auto_20230328_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet',
            old_name='height',
            new_name='height_cm',
        ),
    ]
