# Generated by Django 3.2 on 2023-02-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('activity_level', models.CharField(max_length=50)),
                ('dietary_restriction', models.CharField(max_length=50)),
                ('goal', models.CharField(max_length=50)),
                ('workout_goal', models.CharField(max_length=50)),
            ],
        ),
    ]
